React & Redux group project - Space Travelers' Hub
bilalrajput09/space-travelers-app pull request #36
Opened 2023-05-23 13:26 UTC by bilalrajput09

## Redux: Fetch data and update the Redux store

- Used SpaceX API endpoints:

- Rockets: https://api.spacexdata.com/v4/rockets.
- Missions: https://api.spacexdata.com/v3/missions.

### Project set up.
- Setup redux.
- Fetch and render rockets and missions.
- Create my profile to display current missions and reserved rockets.

2023-05-23 14:27 UTC, Olamarx requested changes
Hi Team, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media3.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

## Highlights
- Linters passed ✔️
- Readme file professional ✔️
- Good use of react-redux methods ✔️
- Good use of react-router-dom's Link tag ✔️

## Required Changes ♻️
_Check the comments under the review._
- [ ] I would remind you of the test, you need to make tests with react test library and jest for unit tests as required in the project.
![image](https://github.com/bilalrajput09/space-travelers-app/assets/86200356/94a60bae-a623-46eb-bc6b-ae6fdb4e828e)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-23 14:27 UTC, Olamarx commented on package.json
> +  },
- [x] I can see you forgot to add react-logger, this is a requirement as it will help to console the state of the app in the redux to the console. You can get help to it [here](https://www.npmjs.com/package/redux-logger)

2023-05-23 14:27 UTC, Olamarx commented on src/components/Rocket.js
> +    </article>
- [ ] I will implore you to design each rocket according to the project requirement. When a reservation is made, you will notice that the location and color of yours is different from the one of the requirement. Even the cancel reservation button has a transparent background.

## Project requirement
![image](https://github.com/bilalrajput09/space-travelers-app/assets/86200356/9396232b-86ad-4800-8795-301bfd4efd0d)

## Your project
![image](https://github.com/bilalrajput09/space-travelers-app/assets/86200356/43b9c1f9-b780-40c0-9ff3-48b84f45b83a)

2023-05-23 14:27 UTC, Olamarx commented on src/components/MyProfile.js
> +            <span>No Mission joined!</span>
Good job on this condition 👍🏼

2023-05-24 08:02 UTC, bilalrajput09 commented on package.json
> +  },
Done ✔✔

2023-05-24 08:02 UTC, bilalrajput09 commented on src/components/Rocket.js
> +    </article>
Done ✔✔

2023-05-24 08:03 UTC, bilalrajput09 commented on src/components/MyProfile.js
> +            <span>No Mission joined!</span>
Thank you so much @Olamarx

2023-05-24 08:25 UTC, abdulhamiid approved these changes
# :green_circle:  Approved! :partying_face:
Hi Team 👋, 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🌟

- ✔️ Descriptions are descriptive
- ✔️ Linters checks are passing
- ✔️ Use Git Flow
- ✔️ Meaningful commit messages.

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-24 09:14 UTC, merged